### ISSUE TITLE
OCR treaty pdfs

### ISSUE THREAD

**Issue by jhollway** [globalgov/manypkgs#18]
Consider image binarization for removing grayscale elements from scanned text for improved optical character recognition.

How does quanteda do this?

**Comment by jhollway** [comment]
`{pdftools}`, `{tesseract}`, or both?

- https://www.r-bloggers.com/2016/08/extracting-content-from-pdf-files/
- https://www.r-bloggers.com/2019/03/get-text-from-pdfs-or-images-using-ocr-a-tutorial-with-tesseract-and-magick/
- https://www.r-bloggers.com/2017/07/how-to-do-optical-character-recognition-ocr-of-non-english-documents-in-r-using-tesseract/

**Comment by henriquesposito** [comment]
@jhollway do you have any specific examples of datasets you want to incorporate that have their treaty texts in pdf formats? I will start to work on a function for OCR pdf texts. Thank you.

**Comment by jhollway** [comment]
ECOLEX has PDFs.
