### ISSUE TITLE
Improve code_agreements() function 

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/manypkgs#22]
1) Around 15% of the qID generated by `code_agreements()` in IEADB are duplicates when there are actually different treaty. See examples below

[https://app.zenhub.com/files/365543800/c76d63e5-71c5-4dbb-98d9-9528b1b42fd0/download](https://app.zenhub.com/files/365543800/c76d63e5-71c5-4dbb-98d9-9528b1b42fd0/download)

2) `code_linkage()` function does not link properly to the "mother" treaty: the function is supposed to link any amendments/protocols to its "mother" treaty, which should be an agreement (not a P or E like in the examples below). It often happens that the "mother" treaty is not in the dataset or that the title is too different from the amendment/protocol so the function does not recognized them as part of one family. 

[https://app.zenhub.com/files/365543800/498187ab-a450-4a71-b013-de4524dd1764/download](https://app.zenhub.com/files/365543800/498187ab-a450-4a71-b013-de4524dd1764/download)

3) `code_type()` sometimes identifies the wrong type of treaty (e.g. protocols instead of amendement)

4) The number referring to a protocol or amendment in qID is often wrong (e.g. 20070921P1 should be 20070921P100)

**Comment by jhollway** [comment]
@EstherPeev can you please add each of these (also) as separate issues? That would help tracking progress etc

**Comment by henriquesposito** [comment]
These issues have mostly been solved since, I think. I will close this issue.
