### ISSUE TITLE
Develop code_agreements to differently weight various identifying information

### ISSUE THREAD

**Issue by jhollway** [globalgov/manypkgs#23]

**Comment by jhollway** [comment]
E.g. Document type > subject, so two agreements can have the same subject but one is a convention and another is a protocol and so are considered separate...

**Comment by jhollway** [comment]
E.g. year > day, so two agreements with the same year but a different day, especially if one is generic (-01-01) or swapped (-02-03 vs -03-02), then candidates for similarity...

**Comment by EstherPeev** [comment]
@jhollway I have prepared more examples on how code_agreements() should weight identifying information. Please let me know if anything is unclear.

![image.png](https://images.zenhubusercontent.com/5ff2de14fb5a58fc49c60af6/41e1ce40-2fee-4e72-b26d-92cbb4ce598f)

**Comment by jhollway** [comment]
So how are these orderings transitive? E.g. rule #3 is year > acronym but rule #7 is acronym > year? Can you or @henriquesposito maybe construct this as a flowchart?

**Comment by EstherPeev** [comment]
So here is the flowchart on which identifying information weight more than others with a small explanatory notes. 

![Capture d’écran 2021-08-25 à 11.24.16.png](https://images.zenhubusercontent.com/5ff2de14fb5a58fc49c60af6/1ba6be0b-aa9e-48c4-aadf-23a45b46b039)

@jhollway Is it better in that way?

**Comment by henriquesposito** [comment]
I will start on a code_similar() function that checks for similar qIDs internally.
