### ISSUE TITLE
Update push release workflow template to download qData and README to run related code chunks

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manypkgs#55]
To avoid merge issues with GitHub, qData download from GitHub has been commented out in push release templates and code chunks that refer to qData are not run in README files. Once qData is on CRAN, this should no longer pose any issues and the files can be restored to work with qData

**Comment by jhollway** [comment]
`{manydata}` is now on CRAN. Can we close this issue?

**Comment by henriquesposito** [comment]
I have now updated all many package description files to download manydata and the README files to run manydata related code chunks. These changes have also been made in the templates for new many packages.
