### ISSUE TITLE
Improve how split_treaty() helper function works on treaties other than agreements (e.g. declaration, exchange of notes, amendements)

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/manypkgs#69]
Treaties other than agreements do not have articles so the function does not split the treaty text. Therefore, some remain very long and unusable. Here are some examples: 

* Declaration
http://www.ecuanex.net.ec/cpps/declarac.html

* Exchange of notes
https://iea.uoregon.edu/treaty-text/4335
https://iea.uoregon.edu/treaty-text/2637
https://iea.uoregon.edu/treaty-text/94

* Amendments 
https://iea.uoregon.edu/treaty-text/3184
https://iea.uoregon.edu/treaty-text/2645
https://iea.uoregon.edu/treaty-text/2635

**Comment by henriquesposito** [comment]
There is an extra argument for identifying treaty type now and, if specified, returns only those treaties. It still needs some upgrades for the dictionary to identify types, but works well for thetime being!
