### ISSUE TITLE
Possible data size issue with code_memberships()

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manypkgs#75]
`code_memberships()` and `get_articles()` run into errors (C stack usage too close to the limit) when used on manytrade AGR_TXT texts data, which might be due to large data size

**Comment by henriquesposito** [comment]
The issue here is with the get_article() function which takes too much memory (above the limit at times) when running on large text databases. I am currently re-working get_articles() to make it less recursive and more efficient. Thank you.

**Comment by henriquesposito** [comment]
I have been re-working the function in the past couple of days, and I think the memory issue has been fixed by altering how the function works. However, I still need to get the function returns as expected.

**Comment by henriquesposito** [comment]
The get_articles() function is fixed, I just tested in manytrade and all works on my side.
