### ISSUE TITLE
Improve code_memberships() and code_termination() functions

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manypkgs#76]
These functions work, but it seems that thy miss some of the clauses within agreements that discuss these. To improve these functions we need to rework how these clauses are coded within the function, as well as we might need to improve the dictionary matching for get_articles(), the entity recognition from code_entity(), and the domain coding from code_domains().

**Comment by jaeltan** [comment]
`code_memberships()` now `code_accession_terms()`
