### ISSUE TITLE
Make standardise_dates safer

### ISSUE THREAD

**Issue by BBieri** [globalgov/manypkgs#77]
When running preparation scripts, we sometimes run into wrongly coded data, among which can be dates. An example of this can be found in the ARCHIGOS gnevar dataset where I corrected the birthdate for Didier Burkhalter from `1960-04-1970` to the actual value of `1960-04-17`. 

Identifying these wrongly coded variables will be key for future contributors. Hence, we could implement a warning whenever "strange" dates are detected by `standardize_dates()`. What do you think @jhollway @henriquesposito

**Comment by jhollway** [comment]
Sure, 'strange' dates can be reported, though corrections should be either requested from the original data provider or added to some new dataset, e.g. `gnevar`

**Comment by BBieri** [comment]
Thanks @henriquesposito, will take a look at it today!

**Comment by henriquesposito** [comment]
Thank you @BBieri ! Also, now that I am thinking about this, it may be redundant to keep this wrapper function in manypkgs as we could simply use messydates. What do you think?

**Comment by BBieri** [comment]
Agreed! `standardise_dates()` is being simply a wrapper does not bring anything to the table in terms of functionality. The only thing I am worried about is the dependency management of the data packages. Since some of them have functions that scrape and format data from e.g. `{cshapes}`, they will gain one additional dependency when we do the switch.

What do you think @henriquesposito ?

**Comment by BBieri** [comment]
Thanks for the input! That works, I'll push the changes shortly.
