### ISSUE TITLE
openNLPmodels.en is no longer directly available from source

### ISSUE THREAD

**Issue by BBieri** [globalgov/manypkgs#81]
An external dependency of the `{entity}` package, `{openNLPmodels.en}` is no longer available for direct installation from CRAN or from [source](http://datacube.wu.ac.at) and needs to be installed from [its GitHub repository](https://github.com/cran/openNLPmodels.en). While this is not an immediate issue for `{manypkgs}` it might be confusing for first-time contributors.

*Edit*: the version on GitHub is ancient and does not contain the required models. This breaks the `code_` functions.

**Comment by henriquesposito** [comment]
Thank you @BBieri for the great catch! If I am not mistaken, open nlp was removed from CRAN a while ago and their GitNub repo has long been inactive...

For integrating the models, as I see, we have three choices. We can just change the data download link to the correct web library in the function (https://opennlp.apache.org/models.html). We can use alternative GitHub based repositories/packages and re-work the function to extract coded entities only (https://opennlp.apache.org/models.html). Or, if the size is not an issue, we can add the file to the package itself (as long as we have permission to do so/cite). What do you think?

**Comment by henriquesposito** [comment]
Actually, I just re-tested the link and the opennlp data/model is available again! Please double check but I think it might have been an issue with the datacube repository (https://datacube.wu.ac.at/src/contrib/).
