### ISSUE TITLE
Issue export_data() function related to bibtex dependency

### ISSUE THREAD

**Issue by AndersIHEID** [globalgov/manypkgs#88]
Here is the error:

 manypkgs::export_data(HUGGO, database = "agreements",
+                       URL = c("https://wits.worldbank.org/gptad/library.aspx",
+                               "http://rtais.wto.org/UI/PublicMaintainRTAHome.aspx",
+                               "https://edit.wti.org/app.php/document/investment-treaty/search",
+                               "https://github.com/mappingtreaties/tota.git"))
✔ Setting active project to '/Users/andersviemose/Documents/GitHub/manytrade'
ℹ Found an existing 'agreements' database.
  Imported it ready to update.
ℹ Found an existing 'HUGGO' dataset.
  This will be overwritten.
 Error in bibtex::do_read_bib(file, encoding = .Encoding) : 
argument "srcfile" is missing, with no default
3.
bibtex::do_read_bib(file, encoding = .Encoding)
2.
RefManageR::ReadBib(file = paste0("data-raw/", database, "/", 
dataset_name, "/", dataset_name, ".bib")) at data_export.R#65
1.
manypkgs::export_data(HUGGO, database = "agreements", URL = c("https://wits.worldbank.org/gptad/library.aspx", 
"http://rtais.wto.org/UI/PublicMaintainRTAHome.aspx", "https://edit.wti.org/app.php/document/investment-treaty/search", 
"https://github.com/mappingtreaties/tota.git"))

**Comment by henriquesposito** [comment]
This was a local issue. We can update the function later on if needed.
