### ISSUE TITLE
Duplicate manyIDs

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manypkgs#89]
Some agreements in manyenviron and manytrade have duplicate manyIDs for different agreements that have different titles.

**Comment by delmoralsu** [comment]
manyenviron
**Different treaties:**
HUGGO[3568, ] manyID = BRA-CRI_2008P **/** Title = Complementary Agreement To The Technical Cooperation Agreement Between The Government Of The Federative Republic Of Brazil And The Government Of The Republic Of Costa Rica For Implementation Of The Project Management And Conservation Of Power Plants **/** Beg = 2008-07-30

HUGGO[3569, ] manyID = BRA-CRI_2008P **/** Title = "Complementary Agreement to the Technical Cooperation Agreement between the Government of the Republic of Costa Rica and the Government of the Federative Republic of Brazil for the Implementation of the Accreditation Project of the Chemical Laboratory of the Oil Control Area of the Service Center LIMAT **/** Beg = 2008-07-30

HUGGO[3570, ] manyID = BRA-CRI_2008P **/** Title = Complementary Agreement To The Technical Cooperation Agreement Between The Government Of The Republic Of Costa Rica And The Government Of The Federative Republic Of Brazil For The Implementation Of The Project On Alternatives Biofuel Production **/** Beg = 2008-07-30

HUGGO[3158, ] manyID = SEN-EC_2002A **/** Title = Agreement In The Form Of Exchange Of Letters Concerning The Extension Of The Protocol Establishing The Fishing Opportunities And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Senegal On Fishing Off The Coast Of Senegal For The Period From 1 May 2001 To 31 July 2001 **/** Beg = 2002-06-28 (I have not been able to verify the dates)

HUGGO[3157, ] manyID = SEN-EC_2002A **/** Title = Agreement In The Form Of Exchange Of Letters Concerning The Extension Of The Protocol Establishing The Fishing Opportunities And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Senegal On Fishing Off The Coast Of Senegal For The Period From 1 August 2001 To 31 December 2001 **/** Beg = 2002-06-28 (I have not been able to verify the dates)

HUGGO[2570, ] manyID = GIN-EC_1995P **/** Protocol Establishing For The Period From 1 January 1990 To 31 December 1991 The Fishing Rights And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Guinea On Fishing Off The Guinean Coast **/** Beg = 1990-08-12

HUGGO[2571, ] manyID = GIN-EC_1995P **/** Title = Protocol Establishing For The Period From 1 January 1992 To 31 December 1993 The Fishing Rights And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Guinea On Fishing Off The Guinean Coast **/** Beg = 1992-12-26

HUGGO[2572, ] manyID = GIN-EC_1995P **/** Title = Protocol Establishing For The Period From 1 January 1994 To 31 December 1995 The Fishing Rights And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Guinea On Fishing Off The Guinean Coast **/** Beg = 1995-12-24

**Same treaties:**

HUGGO[499, ] manyID = CDSMMZ_1954P20 **/** Title = Complementary Convention To The Declaration Of Sovereignty Over The 200 Mile Maritime Zone **/** Beg = 1954-12-04 (I verified this row)

HUGGO[498, ] manyID = CDSMMZ_1954P20 **/** Title = Complementary Agreement To The Declaration Of Sovereignty Over The 200 Mile Maritime Zone **/** Beg = 1954-12-04

**Comment by henriquesposito** [comment]
Thank you @AndersIHEID @delmoralsu ! Please keep on adding the false duplicate manyIDs as they show up! 

@jaeltan it appears that the duplication issue occurs mostly for bilateral agreements... I am not sure just yet how to proceed, but I know we have certain unctions to code issue-domain and actions from agreement titles that could be added in these cases. Please let me know of you have any ideas! Thank you.

**Comment by jaeltan** [comment]
Resolving differences in manyID for the same treaties:
* Standardise states' names in treaty titles with `manypkgs::standardise_titles()`
* recode manyIDs in manyenviron HUGGO dataset so that bilateral treaties have activity coded

**Comment by delmoralsu** [comment]
### Repetitions of manyID

#### 01/12/22
- HUGGO[230, ] manyID = DEU-DNK[BGF]_1922A **/** Title = Agreement Between Denmark And Germany Regarding Fisheries And Reed Cutting In The Rudebol Lake And The Videa River And Regarding The Cutting Of Hay And Bulrushes In The Gotteskoog Together With Final Protocol **/** Beg = 1922-04-10 **/** treatyID = DEU-DNK[BGF]_1922A

- HUGGO[231, ] manyID = DEU-DNK[BGF]_1922A **/** Title = Agreement Between Denmark And Germany Regarding Fisheries On The Breitgrund With Final Protocol **/** Beg = 1922-04-10 **/** treatyID = DEU-DNK[FBF]_1922A

- HUGGO[228, ] manyID = DEU-DNK[BGF]_1922A **/** Title = Agreement Between Denmark And Germany For The Settlement Of Questions Relating To Watercourses And Dikes On The German-Danish Frontier **/** Beg = 1922-04-10 **/** treatyID = DEU-DNK[GDF]_1922A


- HUGGO[236, ] manyID = FIN-RUS[FRH]_1922A **/** Title = Convention Between Finland And Russia With Regard To Fishing And Sealing On Lake Ladoga Helsingfors **/** Beg = 1922-10-28 **/** treatyID = FIN-RUS[LLH]_1922A

- HUGGO[237,] manyID = FIN-RUS[FRH]_1922A **/** Title = Convention Between The Union Of Soviet Socialist Republics And Finland Concerning The Maintenance Of River Channels And The Regulation Of Fishing On Watercourses Forming Part Of The Frontier Between Russia And Finland **/** Beg = 1922-10-28 **/** treatyID = FIN-RUS[PFR]_1922A


- HUGGO[338,] manyID = FIN-NOR[FSP]_1938A **/** Title = Convention Between Finland And Norway Regarding New Regulations For Fishing In The Pasvik River (Pasvikelva) **/** Beg = 1938-04-21 **/** treatyID = FIN-NOR[FSP]_1938A

- HUGGO[339,] manyID = FIN-NOR[FSP]_1938A **/** Title = Convention Between Finland And Norway Regarding New Regulations For Fishing In The Tana River **/** Beg = 1938-04-21 **/** treatyID = FIN-NOR[FST]_1938A

- HUGGO[487,] manyID = IND-NPL[IWS]_1954A **/** Title = Agreement Between The Governments Of India And Nepal For The Construction Of Minor Irrigation Works And Water Supply Projects **/** Beg = 1954-07-14 **/** treatyID = IND-NPL[IWS]_1954A

- HUGGO[479,] manyID = IND-NPL[IWS]_1954A **/** Title = Agreement Between The Government Of India And The Government Of Nepal On The Kosi Project **/** Beg = 1954-04-25 **/** treatyID = IND-NPL[KOS]_1954A

- HUGGO[414,] manyID = HUN-RUS[RAF]_1950A **/** Title = Treaty Between The Government Of The Union Of Soviet Socialist Republics And The Government Of The Hungarian Peoples Republic Concerning The Regime Of The Soviet-Hungarian State Frontier And Final Protocol **/** Beg = 1950-02-24 **/** treatyID = HUN-RUS[SFF]_1950A

- HUGGO[420,] manyID = HUN-RUS[RAF]_1950A **/** Title = Convention Between The USSR And Hungary Concerning Measures To Prevent Floods And To Regulate The Water Regime In The Area Of The Frontier **/** Beg = 1950-06-09 **/**  treatyID = HUN-RUS[RAF]_1950A

- HUGGO[627,] manyID = FSHBBF_1959A **/** Title = Convention Concerning Fishing In The Black Sea **/** Beg = 1959-07-07 **/** treatyID = FSHNBS_1959A

- HUGGO[630,] manyID = FSHBBF_1959A **/** Title = Convention Concerning Fishing In The Bidassoa And The Bay of Figuier **/** Beg = 1959-07-14 **/** treatyID = 	
FSHBBF_1959A

- HUGGO[539,] manyID = CAN-IND[CAR]_1956A **/** Title = Agreement On The Canada-India Colombo Plan Atomic Reactor Project **/** Beg = 1956-04-28 **/** treatyID = CAN-IND[CAR]_1956A

- HUGGO[556,] manyID = CAN-IND[CAR]_1956A **/** Title = Agreement On The Canada-India Colombo Plan Kundah Hydroelectric Power Project **/** Beg = 1956-12-29 **/** treatyID = CAN-IND[CKH]_1956A

- HUGGO[751,] manyID = CAN-USA[DBD]_1964N **/** Title = Exchange Of Notes Constituting An Agreement Between Canada And The United States Of America Regarding Sale Of Canadas Entitlement To Downstream Benefits Under The Treaty Relating To Cooperative Development Of The Water Resources Of The Columbia River Basin **/** Beg = 1964-01-22 **/** treatyID = CAN-USA[DBD]_1964N

- HUGGO[780] manyID = CAN-USA[DBD]_1964N **/** Title = Exchange Of Notes Constituting An Agreement Between Canada And The United States Of America Confirming The Entry Into Force Of The Protocol Attached To The Agreement Of 1964 Concerning Treaty Relating To Cooperative Development Of The Water Resources Of The Columbia River Basin **/** Beg = 1964-09-16 **/** treatyID = CAN-USA[FAD]_1964N

- HUGGO[1130,] manyID = RUS-USA[PCF]_1973A **/** Title = Agreement Between The Government Of The United States Of America And The Government Of The Union Of Soviet Socialist Republics Relating To Fishing Operations In The North Eastern Pacific Ocean **/** Beg = 1973-02-21 **/** treatyID = RUS-USA[UFO]_1973A

- HUGGO[1132,] manyID = RUS-USA[PFC]_1973A **/** Title = Agreement Between The Government Of The United States Of America And The Government Of The USSR Relating To The Consideration Of Claims Resulting From Damage To Fishing Vessels Or Gear And Measures To Prevent Fishing Conflicts **/** Beg = 1973-02-21 **/** treatyID = RUS-USA[PFC]_1973A

- HUGGO[1278,] manyID = RUS-USA[HSA]_1975A **/** Title = Agreement Between The Government Of The United States Of America And The Government Of The Union Of Soviet Socialist Republics On Certain Fishery Problems On The High Seas In The Western Areas Of The Middle Atlantic Ocean **/** Beg = 1975-02-26 **/** treatyID =  RUS-USA[HSA]_1975A

- HUGGO[1343,] manyID = RUS-USA[HSA]_1975A **/** Title = Agreement Effected By Exchange Of Notes Extending The Agreement Between The Government Of The United States Of America And The Government Of The Union Of Soviet Socialist Republics On Certain Fishery Problems On The High Seas In The Western Areas Of The Middle Atlantic Ocean **/** Beg = 1975-12-30 **/** treatyID =  RUS-USA[HSA]_1975A

- HUGGO[1305,] manyID = GU14US_1975A **/** Title = Agreement Between The Government Of The United States Of America And The Government Of The Polish Peoples Republic Regarding Fisheries In The North Eastern Pacific Ocean Off The Coast Of The United States **/** Beg = 1975-05-30 **/** treatyID = GU14US_1975A

- HUGGO[1339,] manyID = GU14US_1975A **/** Title = Agreement Between The Government Of The United States Of America And The Government Of The Polish Peoples Republic Regarding Fisheries In The North Eastern Pacific Ocean Off The Coast Of The United States **/** Beg = 1975-12-16 **/** treatyID = GU14US_1975A

- HUGGO[863,] manyID = DNK-EC[ECH]_1967N **/** Title = Exchange Of Letters Constituting An Agreement Between Denmark And The European Community Concerning Concessions From The European Economic Community On Herring **/** Beg = 1967-06-30 **/** treatyID = DNK-EC[ECH]_1967N

- HUGGO[864] manyID = DNK-EC[ECH]_1967N **/** Title = Exchange Of Letters Constituting An Agreement Between Denmark And The European Community Concerning Concessions From The European Economic Community On Tuna **/** Beg = 1967-06-30 **/** DNK-EC[ECT]_1967N

- HUGGO[1296] manyID = CAN-NOR[CSS]_1975N **/** Title = Exchange Of Notes Between The Government Of Canada And The Government Of Norway Amending The Agreement Between The Government Of Canada And The Government Of Norway On Sealing And The Conservation Of The Seal Stocks In The North West Atlantic **/** Beg = 1975-04-23 **/** treatyID = CAN-NOR[CSS]_1975N

- HUGGO[1338] manyID = CAN-NOR[CSS]_1975N **/** Title = Exchange Of Notes Between The Government Of Canada And The Government Of Norway Amending The Agreement Between The Government Of Canada And The Government Of Norway On Sealing And The Conservation Of The Seal Stocks In The North West Atlantic **/** Beg = 1975-12-12 **/** treatyID = CAN-NOR[CSS]_1975N

- HUGGO[857,] manyID = JPN-USA[FSF]_1967N **/** Title = Exchange Of Notes Constituting An Agreement Between The United States Of America And Japan Concerning Certain Fisheries Off The Coast Of The United States Of America **/** Beg = 1967-05-09 **/** treatyID = JPN-USA[NCF]_1967N

- HUGGO[858,] manyID = JPN-USA[FSF]_1967N **/** Title = Exchange Of Notes Constituting An Agreement Between The United States Of America And Japan Concerning Salmon Fisheries **/** Beg = 1967-05-09 **/** treatyID = JPN-USA[FSF]_1967N

- HUGGO[3158, ] manyID = SEN-EC[CFP]_2002A  **/** Title = Agreement In The Form Of Exchange Of Letters Concerning The Extension Of The Protocol Establishing The Fishing Opportunities And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Senegal On Fishing Off The Coast Of Senegal For The Period From 1 May 2001 To 31 July 2001 **/** Beg = 2002-06-28  (I have not been able to verify this date) **/** treatyID = SEN-EC[CFP]_2002A

- HUGGO[3157, ] manyID = SEN-EC[CFP]_2002A **/** Title = Agreement In The Form Of Exchange Of Letters Concerning The Extension Of The Protocol Establishing The Fishing Opportunities And Financial Compensation Provided For In The Agreement Between The European Economic Community And The Government Of The Republic Of Senegal On Fishing Off The Coast Of Senegal For The Period From 1 August 2001 To 31 December 2001 **/** Beg = 2002-06-28 (I have not been able to verify this date) **/** treatyID = SEN-EC[CFP]_2002A

- HUGGO[3569, ] manyID = BRA-CRI_2008P **/** Title = Complementary Agreement to the Technical Cooperation Agreement between the Government of the Republic of Costa Rica and the Government of the Federative Republic of Brazil for the Implementation of the Accreditation Project of the Chemical Laboratory of the Oil Control Area of the Service Center LIMAT **/** Beg = 2008-07-30 **/** treatyID = BRA-CRI[ASL]_2008P

- HUGGO[3570, ] manyID = BRA-CRI_2008P **/** Title = Complementary Agreement To The Technical Cooperation Agreement Between The Government Of The Republic Of Costa Rica And The Government Of The Federative Republic Of Brazil For The Implementation Of The Project On Alternatives Biofuel Production **/** Beg = 2008-07-30 **/** treatyID = BRA-CRI[ABP]_2008P

**Comment by henriquesposito** [comment]
@jaeltan it seems that, sometimes, we are being too "fuzzy" with the matching of bilateral treaties. Please let me know if you have any solutions/suggestions on how to fix this... As a suggestion, on my side, we can reduce the similarity score for matching or having different threshold/methods for matching bilateral and multilateral treaty IDs.
