### ISSUE TITLE
Condense and refactor code_states()

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manypkgs#90]
Helper functions for `code_states()` have some duplicate functionality that could be removed

**Comment by jaeltan** [comment]
The current `code_parties` function does not match and replace single state names (in English or French) in a variable in the dataset. The function needs to match the given state name (only one in each cell) to the countryregex list and return its abbreviation (see for eg. GPTAD_MEM$stateID and GPTAD_MEM$StateName in manytrade).

**Comment by henriquesposito** [comment]
@jaeltan I have updated code_states() by adding a replace argument that should fix the issues you mention above. Could you please double check that it does what you would like and if there are any other improvements you would like me to add? Thank you!
